import Head from "next/head";
import styled from "styled-components";
import { Navbar } from "src/components/Navbar";
import { Button, Flex } from "@mantine/core";

const StyledHeroSection = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  height: 80vh;
`;

const StyledTitle = styled.h1`
  display: flex;
  align-items: center;
  font-size: 64px;
  font-weight: 800;
  gap: 8px;

  background: linear-gradient(180deg, #fff 25%, rgba(255, 255, 255, 0.7) 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Herowand: Innovation Meets with Tools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <StyledHeroSection>
        <img width="200" src="/logo.webp" alt="" />
        <StyledTitle>Innovation Meets with Tools</StyledTitle>
        <Flex gap="sm">
          <Button
            component="a"
            target="_blank"
            rel="noopener noreferrer"
            href="https://linkedin.com/company/Herowand"
            size="lg"
            variant="gradient"
            gradient={{ from: "purple", to: "red" }}
          >
            LinkedIn
          </Button>
          <Button
            component="a"
            target="_blank"
            rel="noopener noreferrer"
            href="https://github.com/Herowand"
            size="lg"
            variant="gradient"
            gradient={{ from: "red", to: "pink" }}
          >
            GitHub
          </Button>
        </Flex>
      </StyledHeroSection>
    </>
  );
}
