import { CardGradient } from "@/components/CardGradient";
import { HeroText } from "@/layout/Hero";
import Layout from "@/layout/Layout";
import {
  Center,
  Container,
  Grid,
  Stack,
  Text,
  Button,
  Title,
} from "@mantine/core";
import Head from "next/head";

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Herowand: Innovation Meets with Tools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroText />
      <Container>
        <Stack align="center" spacing="xs">
          <Text fw="bold" fz={20} c="white" opacity={0.3}>
            Backed by
          </Text>
          {/* <Flex gap="xl">
            {["Google", "Uber", "Trendyol", "Amazon"].map((company) => (
              <Text color="dimmed" fz={30} fw="bolder" key={company}>
                {company}
              </Text>
            ))}
          </Flex> */}
          <Button
            variant="light"
            component="a"
            href="https://patreon.com/Herowand"
          >
            Become Backer
          </Button>
        </Stack>
      </Container>
      <Container className="repeating-grid" fluid>
        <Center pt={150} pb={300} component="section" id="apps">
          <Stack>
            <Title py="xl" color="white" order={1}>
              Created so far,
            </Title>
            <Grid>
              <Grid.Col sm={6}>
                <CardGradient
                  href="https://jsoncrack.com"
                  image="https://cdn-1.webcatalog.io/catalog/json-crack/json-crack-icon-filled-256.png?v=1675593486109"
                  title="JSON Crack"
                  description="Visualize your JSON data instantly into graphs."
                />
              </Grid.Col>
              <Grid.Col sm={6}>
                <CardGradient title="Soon" description="What could it be?" />
              </Grid.Col>
            </Grid>
          </Stack>
        </Center>
      </Container>
    </Layout>
  );
}
